<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:msxsl="urn:schemas-microsoft-com:xslt" xmlns:local="clr-namespace:DevelopersWin.VoteReporter;assembly=DevelopersWin.VoteReporter" exclude-result-prefixes="msxsl i local"
>
	<xsl:output method="html" indent="no" />

	<xsl:template match="local:VoteReport"><xsl:variable name="Date" select="msxsl:format-date( @Created, 'dddd, MMMM d, yyyy')" /><xsl:variable name="TotalUbiquitous" select="format-number(local:VoteReport.Groups/local:VoteGroupView[1]//local:VoteCount/@Count, '###,###')" />TITLE:
======
Weekly Vote Report for <xsl:value-of select="$Date" />

BODY:
=====
| Title 	| Last Week 	| <span class="new">New Votes</span> 	| Total 	|
|-------	|:-----------:|:-----------:|:-------:|
<xsl:apply-templates />
		
This report is generated by a [Xaml-Powered Application](https://imgflip.com/i/h6ho2) hosted in [GitHub](https://github.com/DevelopersWin/VoteReporter).
		
Summary:
========
A new weekly vote report is out! Featuring vote totals for a <xsl:for-each select="local:VoteReport.Groups/local:VoteGroupView"><xsl:if test="position()=last()"><xsl:text>and </xsl:text></xsl:if><xsl:value-of select="@Title" /> (+<xsl:value-of select=".//local:VoteCount/@Delta" /> New/<xsl:value-of select="format-number(.//local:VoteCount/@Count, '###,###')" /> Total)<xsl:if test="not(position()=last())"><xsl:text>, </xsl:text></xsl:if></xsl:for-each>.
Message:
========
Weekly Vote Report for <xsl:value-of select="$Date" />: <xsl:value-of select="$TotalUbiquitous" /> Cumulative Votes for a Ubiquitous #dotNET Client Model. 

Dark O' Thirty:
===============
.@satyanadella @VisualStudio @windowsdev <xsl:value-of select="$TotalUbiquitous" /> votes for a ubiquitous #dotNET. Will you #empower $MSFT #developers?

Disqus Comment:
Please show your support by liking and/or re-tweeting our kind, weekly ping to the Big Three there @ MSFT: 
</xsl:template>

	<xsl:template match="local:VoteGroupView">| **<xsl:value-of select="@Title" />** | **<xsl:value-of select="format-number( number(.//local:VoteCount/@Count)-number(.//local:VoteCount/@Delta), '###,###' )" />** | <span class="new">**<xsl:value-of select=".//local:VoteCount/@Delta" />**</span> | **<xsl:value-of select="format-number( .//local:VoteCount/@Count, '###,###' )" />** |<xsl:text>&#10;</xsl:text><xsl:apply-templates select="local:VoteGroupView.Votes/local:VoteView" /></xsl:template>
	
	<xsl:template match="local:VoteView">| [<xsl:value-of select="@Title" />](<xsl:value-of select="@Location" />) | <xsl:value-of select="format-number( number(.//local:VoteCount/@Count)-number(.//local:VoteCount/@Delta), '###,###' )" /> | <span class="new"><xsl:value-of select=".//local:VoteCount/@Delta" /></span> | **<xsl:value-of select="format-number( .//local:VoteCount/@Count, '###,###')" />** |<xsl:text>&#10;</xsl:text></xsl:template>
</xsl:stylesheet>